name: Deploy to EC2

on:
  push:
    branches:
      - main  # or your preferred branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to EC2
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.EC2_HOST }}
        REMOTE_USER: ${{ secrets.EC2_USER }}
        TARGET: ${{ secrets.EC2_TARGET_PATH }}

    - name: Start application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd ${{ secrets.EC2_TARGET_PATH }}
          source venv/bin/activate
          pip3 install -r requirements.txt
          nohup flask run --host=0.0.0.0 --port=5000 > flask.log 2>&1 &
